auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  max_query_length: 10y

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2025-02-26
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  aws:
    s3: s3://${AWS_ACCESS_KEY}:${AWS_SECRET_ACCESS_KEY}@ap-northeast-2/earlybird-loki
